### PR TITLE
Support groups

### PR DESCRIPTION
**Pull request by Max104t**
Added the following Group functions:
- Accept, Reject invites
- Leave group
- List broadcasts by clicking on group title
- view owner and invitee by clicking on their user_id

TODO:
- view group members by clicking on member count

Known Issues:
- Accordion interface is flaky. I don't know how to fix it!

### CODE REVIEW

**Comment by kewalsk** [comment]
One bug I have found is when user has no invitations:

`PeriscopeApiWrapper.js:123 channels https://channels.pscp.tv/v1/users/***/pending-invites :  Object {ChannelsWithMembership: null, Cursor: "", HasMore: false}`
`Groups.js:136 Uncaught TypeError: Cannot read property 'length' of nullGroups.js:136 (anonymous function)`
`PeriscopeApiWrapper.js:124 GM_xmlhttpRequest.onloadPeriscopeApiWrapper.js:22 (anonymous function)`
`events.js:70 emitNoneevents.js:147 emit_stream_readable.js:891 (anonymous function)node.js:375 _tickCallback`

and there is no further call to get group memberships

**Comment by kewalsk** [comment]
I'd like to suggest to rearrange UI for better usability. The group invites, list of user groups and group broadcasts have different functionalities, so it would be much better to make separate main menu items for them. 

- The list of invites is fine - accept and reject buttons for each, only the picture could be smaller - it's not interesting, just a merge profile pictures of few members. It is even not possible to set it when the group is created. The full information about the group inviter would be fine, not just a internal id.

- The user group list should behave like a list of users - when clicked there should be jump to a function similar to User (get by id),  with 3 lists: broadcasts, members, history. The members and history lists should call api on demand (when expanded) because getting these information could take very long time. Some indication the work is in progress is needed to prevent user from clicking over and over again.

- This way a function to show a list of group broadcasts is not necessary because will be part of above. Still the list of group broadcasts can be taken [for one group only](https://github.com/kewalsk/My-OpenPeriscope/wiki/getBroadcastsForChannel)

What do you think?

**Comment by Max104t** [comment]
all are good, but i need to switch to my cordova based port of open periscope.. would it be too much if you pull my branch and revamp the ui? i can fix the bug today... I think fully supporting groups may take a while for example sharing and boradcasting to groups... or creating them... we could take this change and continue to enhance it over the coming weeks... and also find a replacement for my cheesey accordion... 😂

**Comment by gitnew2018** [comment]
You are probably overwhelmed I get it.
It is not ready to pull into master but sure I'm going to take a look and improve it, With a solid base like that, it shouldn't be too hard 😉.

**Comment by Max104t** [comment]
Thanks @gitnew2018 and @kewalsk ..
Also,  I just found out that DELETE/PATCH https://channels.pscp.tv/v1/channels/{cid}/members/{uid} doesn't work all the time.. I like pulling this into another branch than `master` until it is ready..

**Comment by kewalsk** [comment]
I will develop UI refactor in [my devel-groups branch](https://github.com/kewalsk/My-OpenPeriscope/tree/devel-groups).

**Pull request merged**
